name: learn-github-actions
run-name: ${{ github.actor }} is learning Github Actions
on: [push]

jobs:
  runs-on: ubuntu-latest

  initializeDependencies:
    uses: ./.github/workflows/setup-tests.yml
    secrets: inherit

  executeTests:
    needs: initializeDependencies
    strategy:
      matrix:
        browser: ["browserstack:chrome@103.0:Windows 10", "browserstack:chrome@104.0:Windows 10"]

    steps:
      - run: testcafe '${{ matrix.browser }}' --config-file=./.testcaferc.js
        env:
          BROWSERSTACK_BUILD_ID: ${{ secrets.BROWSERSTACK_BUILD_ID }}
          BROWSERSTACK_PROJECT_NAME: ${{ secrets.BROWSERSTACK_PROJECT_NAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
