name: initialize tests

on:
  workflow_call:

jobs:
  initialize-dependencies:

    runs-on: ubuntu-latest

    steps:
    - run: echo '${{ toJSON(runner) }}'

    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: '14'

    - run: npm install

    - run: npm install -g testcafe

    - uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
